version: '3.9'

services:
  Pick_Place:
    image: adrielmicom/pick_place_seminario:3
    runtime: nvidia
    tty: true
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority